### ISSUE TITLE
Running a build generates themes/hugo-theme-monochrome/assets/jsconfig.json

### ISSUE THREAD

**Issue by Nightfirecat** [kaiiiz/hugo-theme-monochrome#16]
As the title mentions, running a build generates this file, which causes a diff in the submodule. Ideally, this should be added to `.gitignore` ala `/assets/jsconfig.json` line to prevent the theme's submodule from becoming dirty after any build. Presently, this requires a call to `git submodule foreach git clean -fd` or similar to remove the generated file.

**Comment by kaiiiz** [comment]
I also have this file, but it's located in the project root folder `/assets/jsconfig.json` instead of `/theme/hugo-theme-monochrome/assets/jsconfig.json`.

Based on the [document](https://gohugo.io/hugo-pipes/js/#import-js-code-from-assets)

> Hugo will, by default, generate a assets/jsconfig.json file that maps the imports. This is useful for navigation/intellisense help inside code editors, but if you don’t need/want it, you can [turn it off](https://gohugo.io/getting-started/configuration/#configure-build).

`jsconfig.json` is useful for navigation/intellisense help inside code editors. I think it's safe to ignore it from git even if the location of the generated file may vary between users. I'll merge it to the dev branch, and it will be available in the next release.
